# This workflow calls the main workflow with custom variables
name: AKS-E2E
run-name: AKS ${{ inputs.downstream_k8s_version || '1.26.10' }} on Rancher v${{ inputs.rancher_version || '2.8-head' }} deployed on ${{ inputs.k3s_version || 'v1.27.9+k3s1' }}

on:
  schedule:
    - cron: "0 4 * * *" # Run every day
  workflow_dispatch: # Allow running manually on demand
    inputs:
      rancher_version:
        description: Rancher version to deploy
        required: true
        type: string
        default: 2.8-head
      k3s_version:
        description: k3s version of local cluster
        required: true
        type: string
        default: v1.27.9+k3s1
      runner_template:
        description: Runner template to use
        default: hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v1
        type: string
      operator_nightly_chart:
        description: Install hosted-provider nightly chart
        default: true
        required: true
        type: boolean
      destroy_runner:
        description: Destroy the auto-generated self-hosted runner
        default: true
        type: boolean
      downstream_cluster_cleanup:
        description: Cleanup downstream clusters after test
        default: true
        type: boolean
      downstream_k8s_version:
        description: Downstream cluster K8s version to test
        default: 1.26.10
      rancher_installed:
        description: Rancher details if already installed
        default: 'hostname/password'
        type: string
      tests_to_run:
        description: Tests to run (p0_provisioning/p0_importing/support_matrix_provisioning/support_matrix_importing)
        type: string
        required: true
        default: p0_provisioning/p0_importing

jobs:
  aks-e2e:
    uses: ./.github/workflows/main.yaml
    secrets: inherit
    with:
      hosted_provider: aks
      rancher_version: ${{ inputs.rancher_version || '2.8-head' }}
      k3s_version: ${{ inputs.k3s_version || 'v1.27.9+k3s1' }}
      operator_nightly_chart: ${{ inputs.operator_nightly_chart == true || (github.event_name == 'schedule' && true) }}
      run_p0_provisioning_tests: ${{ contains(inputs.tests_to_run, 'p0_provisioning') || (github.event_name == 'schedule' && true) }}
      run_p0_importing_tests: ${{ contains(inputs.tests_to_run, 'p0_importing') || (github.event_name == 'schedule' && true) }}
      run_support_matrix_provisioning_tests: ${{ contains(inputs.tests_to_run, 'support_matrix_provisioning') || (github.event_name == 'schedule' && false) }}
      run_support_matrix_importing_tests: ${{ contains(inputs.tests_to_run, 'support_matrix_importing') || (github.event_name == 'schedule' && false) }}
      destroy_runner: ${{ inputs.destroy_runner == true || (github.event_name == 'schedule' && true) }}
      runner_template: ${{ inputs.runner_template || 'hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v1' }}
      downstream_k8s_version: ${{ inputs.downstream_k8s_version || '1.26.10' }}
      rancher_installed: ${{ inputs.rancher_installed || 'hostname/password' }}
      downstream_cluster_cleanup: ${{ inputs.downstream_cluster_cleanup == true || (github.event_name == 'schedule' && true) }}
